# Generated by Django 4.2.12 on 2025-03-04 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='user',
        ),
        migrations.DeleteModel(
            name='HealthData',
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
        migrations.DeleteModel(
            name='user_register',
        ),
    ]
