# Generated by Django 4.2.12 on 2025-03-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0004_remove_reminder_user_delete_healthdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Gardener', 'Gardener'), ('Supervisor', 'Supervisor'), ('HomeOwner', 'HomeOwner')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('climate', models.CharField(blank=True, max_length=50, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
