# Generated by Django 4.2.12 on 2025-03-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Flower', 'Flower'), ('Vegetable', 'Vegetable'), ('Fruit', 'Fruit')], max_length=20)),
                ('characteristics', models.TextField()),
                ('care_requirements', models.TextField()),
                ('age', models.IntegerField(help_text='Age in weeks or months')),
                ('growth_stages', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
