# Generated by Django 4.2.12 on 2025-03-04 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_plant'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlant',
            fields=[
                ('user_plant_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('current_growth_stage', models.CharField(max_length=100)),
                ('health_status', models.CharField(choices=[('Healthy', 'Healthy'), ('Needs Attention', 'Needs Attention'), ('Wilting', 'Wilting'), ('Diseased', 'Diseased')], max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userregister')),
            ],
        ),
    ]
