# Generated by Django 4.2.12 on 2025-03-04 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_userplant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('reminder_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('Watering', 'Watering'), ('Pruning', 'Pruning'), ('Repotting', 'Repotting'), ('Fertilizing', 'Fertilizing')], max_length=100)),
                ('due_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userregister')),
                ('user_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userplant')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('observation_id', models.AutoField(primary_key=True, serialize=False)),
                ('observation_date', models.DateField(auto_now_add=True)),
                ('growth_stage', models.CharField(max_length=100)),
                ('health_indicator', models.CharField(choices=[('Healthy', 'Healthy'), ('Diseased', 'Diseased'), ('Wilting', 'Wilting'), ('Needs Attention', 'Needs Attention')], max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userplant')),
            ],
        ),
    ]
