# Generated by Django 4.2.12 on 2025-03-04 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_reminder_observation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('recommendation_id', models.AutoField(primary_key=True, serialize=False)),
                ('watering_schedule', models.TextField()),
                ('fertilization_plan', models.TextField()),
                ('pest_control_measures', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'Supervisor'}, on_delete=django.db.models.deletion.CASCADE, to='myapp.userregister')),
                ('user_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userplant')),
            ],
        ),
    ]
